/// url = https://www.typescriptlang.org/play?#code/PQKgUABBCMAcCcEC0ECCB3AhgSwC4FMATSZJM8kgIwE8IBZTAY23wCsIBlbAawHsAnTBAAUAAQC2TFqwDOPAZgCUEAMT5MM2ioAO-XuOwz8qygFdsAG1xJsAOzAkVTiAEVT+Gbmy97JAJIAZhDoxgAWmABuxkK41NrG6KHYjKEQhhBC6ILa8YQQsfEQFjzGAAp6BkYANBChvOjBxoyYthAA5vi4+aHGBQlJKWkyabZyhL09wdm5+XH4APwOUABiAhD4AB6Y4toW+ABcaUEhtZHGAAbl+ob4ADwAols7ewAqcwB857X1+bztnRBHttdvg3vFFiRzlDcDISH1AU8QWDjABeCBXSp3Tz8Oxtd5LWaFABKHlMVggaLo1AwOAIhAeiNeHwgwGAEGxuMhUIJ7wgLySwwAju5PN5WultAI6RAAhVusYANoCbBtOyYCwZfheRh7AC6wlCuFw2hk+1Z4wiADpcLxgJJGHI+IJgJhCBEWowiEg+jJGDjtNZNvh+MwjDIkMKPF4fEhoEgACwAVm48eUNAgCokUjYjoU+sNxtNrNVuFCpkolsY+jt2dk8kEih5EAAaiwGj4IABxPAACXLhwLJrNwBhKUtsktAjawDg8DAIGADlAEAA+mv1xv1xAAJq8Uz8CAAYV44wgPeDxk3V7XEAXDnhVJpeCItxevLRLWoS5Aq+vm75UZHhoHi-n+W53tgOxSoSxgAN6AsK6o1I88SMF0AC+MpygA5KIfRICk6p7LYHQyMApheBYMjYfecwQAAGhS6IVDctwciR+LwtuTEYqx8EBCwFiEIctimOIlDBhA6GcXRABaPEsUYty8Up7FtBAAA+ECieJwbvDJhSydACnXEpKl3OZbG4DiJGaRAlC8LwewtPpBnGC8THwaW+C2Icwg+AEZICRYezCSImD8G0IliRJ-DKCivKfvFiW2LQ6G0YUzRhkxCokCh+BoQ8iEWLcj5YM+9L0e8NRqfpVR5RsqG4EVpjqqV1LlXStzbtVED8YJYU6bFUl1Q1TUtW1ZW0i+sm9WpdlDXp1VjQVzX3MV7VPl1RlzdZuJ2Q5TnqLYo1QPlhXra1JVTRVr69Yt-CjbqS5snh4abE1SDBno-BgPC31rJSHXTfSD34mAy5gRuEDLPu3kHhwBAmqBUO3ouoAkLyHDhPwxjUHuB4yE5FFiqatRGkOrKjqE44yJOkUzggLqjCEv1QLyrb4A0RMWCTPhk4ORYjr6NMTlOjPwMAPN86MmP0AIxiHuEIU+aRA4U0L1O0-TbTzouQA

// type MyAwaited<Promise<T>> = T extends Promise<U> ? U : never
// 参考: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

// 没考虑到嵌套的情况
// type MyAwaited<T> = T extends Promise<infer Inner> ? Inner : never

type MyAwaited<T> = T extends {
  then: (onfulfilled: (arg: infer Inner) => any) => any;
}
  ? MyAwaited<Inner>
  : T;
